#### Types of Unclean Data
There are 2 kinds of unclean data
* Dirty data (Data with Quality issues): Dirty dat, also known as low quality data.Low quality data has content issues
- Duplicated data
- Missing data
- Corrupt data
- Ineqaulity data

* Messy data(Data with tidiness issues): Messy data, also known as untidy data. untidy data has structural issues. Tidy data has the following properties:
- Each variable forms a column
- Each observation forms a row
- Each observational unit forms a table

Viewing datasets

### <1/> Write a summary for your data

This is a dataset about 500 patients of which 350 patients participated in a clinical trial. None of the patients were using Novodra(insulin injection) or Auralin (oral tablet insulin) as their primary source of insulin before. All were experiencing elevated HbA1c levels (high blood sugar level)

All 350 patients were treated with Novodra to establis a baseline sugar level and insulin dose. After 4 weeks, which isnt enough time to capture all the change in sugar level (HbA1c) that can be attributed by the switch to Auralin or Novodra:
* 175 patients switched to Auralin for 24 weeks.
* 175 patients used Novodra for 24 weeks.

Adverse reactions is the data about the side effects of using both.

<2/> Write Column descriptions

**Table:** patients
* patient_id
* assigned_sex: male or female
* given_name: first name
* surname
* address
* city
* state
* zip_code
* contact
* birthdate
* weight(lbs)
* height
* bmi: body mass index

**Table:** treatments & treatment_cut
* given_name
* surname
* auralin: the insulin tablet
* novodra: the insulin injection
* hba1c_start: blood sugar level measurement in the beginning of treatment
* hba1c_end: blood sugar level measurement in the end of treatment
* hba1c_change: changes between start and end

**Table:** Adverse reactions
* given_name
* surname
* adverse_reaction: side effects of consumption

### <3/> Add any additional information

## Types of Assessment

There are 2 types of assessment styles:
1. Manual: looking through the data manually in google sheets
2. Programmatic: By using pandas functions such as info, describe or sample

#### Steps in Assessment
* Discover
* Document

exporting data for manual assessment

#### Issues with the datset

1. Dirty Data
* Table -> `Patient`
    - patiend_id = 9 has misspelled name 'Dsvid' instead of 'David' `accuracy`
    - state col sometimes contain full name and sometimes short forms. `consistency`
    - Zip code col has entries with 4 digit , it must be 5 `validity`
    - data missing for 12 patients in these cols:address,city,state,zip_code,country,contact `completion`
    - incorrect for: assigned_sex, zip code, birthdate `validity`
    - duplicate enteries by name 'John Doe' `accuracy`
    - one patient, id=210, has weight=48.8 pounds its miscellenous `accuracy`
    - one patient, id=4, has height=27inch, which is not matching its bmi `accuracy`

* Table -> `treatment` & `treatment_cut`
    - the given_name and surname col in treatment has all lowers but patient given_name and surname col has all capital letters. `consistency`
    - remove 'u' from Auralin & Novodra cols as u represents only unit. `validity`
    - 'hyphen' in auralin & novodra col treated as nan. `validity`
    - missing values in hba1c_change col. `completeion`
    - one duplicate entry by the name 'joseph' `accuracy`
    - hba1c_change has wrong enteries as it  fills with start-end, but the enteries are false when calculating it. `accuracy`

* Table -> `adverse`
    - the given_name and surname col in adverse_reaction has all lowers but patient data has given_name and surname has all capital letters. `consistency`


2. Messy Data
* Table -> `Patient`
    - Contact col contains both phone and email together

* Table -> `treatment` & `treatment_cut`
    - Auralin & Novodra col should be split between 2 cols , start and end dose instead of hyphen

* Table -> `adverse`
    - we shouldnt this table as, it only presents one col, which can add in treatment.

#### Automatic Assessment
* head and tail
* sample
* infor
* isnull
* duplicated
* describe

In [ ]:
# there is someone in patients data whose weight is 48.8 pounds approx. 21kg,let's check he is kid or not

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

bmi value is not matching with the height and weight so its wrong entry

In [ ]:
# In patients data, minimum height is 27inch, which is 2.5 feet approx. we have to check

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

bmi entery is not matching with the height and weight of the person that means its wrong entery

In [ ]:
#treatments.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [ ]:
# max is slightly higher in treatments, so we check
#treatments.sort_values('hba1c_change',na_position='first')
# not much outliers, its normal.

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
49,jackson,addison,-,42u - 42u,7.99,7.51,0.98
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
138,giovana,rocha,-,23u - 21u,7.87,7.38,0.99
32,laura,ehrlichmann,-,43u - 40u,7.95,7.46,0.99
245,wu,sung,-,47u - 48u,7.61,7.12,0.99

we can clearly able to see the hba1c_change data is wrong in tail(5), wrong enteries are put

## *Note:- Assessing Data is an Iterative Process, you cant gain things in one go.*

#### Data Quality Dimensions:-
* Completeness -> is data missing?
* Validity -> is data invalid -> negative height -> duplicate patient id
* Accuracy -> data is valid but not accurate -> weight-> 1kg
* Consistency -> both valid accurate but written differently -> New York and NY

### Order of Severity:
completeness > Validity > Accuracy > Consistency

#### ORDER:
1. Completeness
2. Tidy
3. Validity
4. Accuracy
5. Consistency

Steps Involved in Data Cleaning
* Define
* Code
* Test

## Data Cleaning

Define:
- replace all missing data

Define
- replace all missing values of patients data with no data or wrong data
- we have to perform hba1c_change=hba1c_start-hba1c_end

#### Tidiness: Messy data

Define:
* patients table me contact col me phone and email dono sath me hai
* we have to seperate them out using regex email and phone

Adverse table shouldnt exist independently as its only taking more space